# -*- coding: utf-8 -*-
# Copyright 2017 Jairo Llopis <jairo.llopis@tecnativa.com>
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).

import logging

from odoo import fields, models, api
from odoo.http import request


_logger = logging.getLogger(__name__)


class IrUiView(models.Model):
    _inherit = 'ir.ui.view'

    # TODO: this field can be removed and origin_view_id can be used instead
    multi_theme_generated = fields.Boolean(
        name="Generated from multi theme module",
        readonly=True,
        help="Was this view autogenerated by website_multi_theme?",
    )
    was_active = fields.Boolean(
        help="Indicates if the view was originally active before converting "
             "the single website theme that owns it to multi website mode.",
    )

    # TODO: add fields below to form view
    origin_view_id = fields.Many2one(
        "ir.ui.view",
        string="Copied from",
        help="View from where this one was copied for multi-website"
    )
    copy_ids = fields.One2many(
        "ir.ui.view",
        "origin_view_id",
        string="Copies",
        help="Duplicates of this view"
    )

    @api.model
    def _customize_template_get_views(self, key, full=False, bundles=False):
        """This method is used to prepare items in 'Customize' menu of website Editor"""
        views = super(IrUiView, self)._customize_template_get_views(
            key, full=full, bundles=bundles
        )

        if full:
            return views

        current_website = request.website
        return views.filtered(lambda v: v.website_id == current_website)
